apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: pubgrade-ingress
spec:
  rules:
  - host: {{ .Values.pubgrade_webserver.ingress.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pubgrade-service
            port:
              number: {{ .Values.pubgrade_webserver.port }} 
  tls:
  - hosts:
    - {{ .Values.pubgrade_webserver.ingress.url }}
    secretName: {{ .Values.pubgrade_webserver.ingress.tlsSecrets }}
