gh_access_token="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
cosign_password="XXXXX"
cosign_private_key="""-----BEGIN ENCRYPTED COSIGN PRIVATE KEY-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END ENCRYPTED COSIGN PRIVATE KEY-----"""




